### ISSUE TITLE
是否可以考虑集成百度站内搜索？

### ISSUE THREAD

**Issue by linkerlin** [tomoya92/pybbs#10]
自己用solr搭搜索太费资源了。

**Comment by tomoya92** [comment]
@linkerlin 我集成了solr搜索只是个demo而已，想用的话，可以用solr，不想用的话，可以自己改成直接查询数据库

**Comment by tomoya92** [comment]
@linkerlin 对于你说的站内搜索，到百度站内搜索网站上去新建搜索引擎改改样式，加到页面里就ok了，我就不开发了，见谅http://zn.baidu.com/
