### ISSUE TITLE
根据文档，启动报错

### ISSUE THREAD

**Issue by ATAlanTang** [tomoya92/pybbs#102]
配置好数据源，从co.yiiu.pybbs.PybbsApplication启动，提示
Description:

Field configuration in co.yiiu.pybbs.config.FreemarkerConfig required a bean of type 'freemarker.template.Configuration' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'freemarker.template.Configuration' in your configuration.
请问这个该怎么办？

**Comment by tomoya92** [comment]
你项目下载后，maven编译完成了吗？感觉像是maven没有编译完，依赖没下完

有配置maven环境的话，在终端里运行一下 `mvn clean compile` 如果提示成功了，再启动项目试试

**Comment by ATAlanTang** [comment]
谢谢！我重拉取一次，就可以了。
