### ISSUE TITLE
如果想前后端分离的话，需要修改哪些配置呢？

### ISSUE THREAD

**Issue by 13474076037** [tomoya92/pybbs#103]
前后端分离，提取出前端代码，前后端分别部署，应该修改那些配置呢？谢谢

**Comment by tomoya92** [comment]
目前项目中已经提供了api，但没有前端代码，也就是说要自己开发

接口在文档中有详细描述

现在提供的两套主题都是freemarker开发的，这不是前端语言，是服务端渲染模板

**Comment by 13474076037** [comment]
嗯，非常感谢解答。
