### ISSUE TITLE
Sub-optimal count query for topicMapper.selectAll

### ISSUE THREAD

**Issue by wtune** [tomoya92/pybbs#105]
For finding topics with user information via the automatic paged query [selectAll](https://github.com/tomoya92/pybbs/blob/master/src/main/java/co/yiiu/pybbs/service/impl/TopicService.java#L68), a query counting the total number of rows `selectAll` retrieves will be issued:
```sql
SELECT 
  COUNT(1) 
FROM 
  (
    select 
      t.*, 
      u.username, 
      u.avatar 
    from 
      topic t 
      left join user u on t.user_id = u.id 
    order by 
      t.top desc, 
      t.in_time desc
  ) TOTAL

```
However, since the query use `topic` to **left join** `user` table on **primary key** `u.id`, the final result is the same to query `select count(1) from topic` without any join operator or order by. So the counting query has a chance to be optimized.

**Comment by tomoya92** [comment]
select count (1) This query is done by mybatis-plus framework, I did not write this sql
