### ISSUE TITLE
Sub-optimal count query for commentMapper.selectByUserId

### ISSUE THREAD

**Issue by wtune** [tomoya92/pybbs#106]
For finding comments by user id via the automatic paged query [selectByUserId](https://github.com/tomoya92/pybbs/blob/master/src/main/java/co/yiiu/pybbs/service/impl/CommentService.java#L208), a query counting the total number of rows `selectByUserId` retrieves will be issued:
```sql
SELECT 
  COUNT(1) 
FROM 
  comment c 
  LEFT JOIN topic t ON t.id = c.topic_id 
  LEFT JOIN user u ON t.user_id = u.id 
  LEFT JOIN user uu ON c.user_id = uu.id 
WHERE 
  c.user_id = 3
```
However, since the query use `comment` to **left join** `topic` and `user` table on **primary key** `id`, the final result is the same to query `select count(1) from comment where user_id = 3` without any join operator. So the counting query has a chance to be optimized.

**Comment by tomoya92** [comment]
#105
