### ISSUE TITLE
Sub-optimal count query for commentMapper.selectAllForAdmin

### ISSUE THREAD

**Issue by wtune** [tomoya92/pybbs#107]
For finding comments by user id via the automatic paged query [selectAllForAdmin](https://github.com/tomoya92/pybbs/blob/master/src/main/java/co/yiiu/pybbs/service/impl/CommentService.java#L224), a query counting the total number of rows `selectAllForAdmin` retrieves will be issued:
```sql
SELECT 
  COUNT(1) 
FROM 
  comment c 
  LEFT JOIN topic t ON c.topic_id = t.id 
  LEFT JOIN user u ON u.id = c.user_id 
WHERE 
  c.in_time BETWEEN '2019-10-01' 
  AND '2019-10-31'
```
However, since the query use `comment` to **left join** `topic` and `user` table on **primary key** `id`, the final result is the same to query `select count(1) from comment where in_time BETWEEN '2019-10-01' AND '2019-10-31'` without any join operator. So the counting query has a chance to be optimized.

**Comment by tomoya92** [comment]
#105
