### ISSUE TITLE
Add Index on system_config.`key` to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [tomoya92/pybbs#108]
Missing index on table `system_config` column `key` might make the underlying query issued via [ISystemConfigService#selectByKey](https://github.com/tomoya92/pybbs/blob/7af492ff4ed696fa8027cf1280ff0372e0cf4a66/src/main/java/co/yiiu/pybbs/service/ISystemConfigService.java#L17) slow. Since table `system_config` is mostly read and rarely updated, the performance impact for write operations is acceptable under common cases.

**Comment by tomoya92** [comment]
The data in the system_config table is limited, and it is cached after being queried once in the SystemConfigService. Subsequent queries will not be queried in the database unless the data in the system_config table changes, so this index is the same whether it is added or not.
