### ISSUE TITLE
关于api的一些问题

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#11]
话题详情
GET: /api/t/:id

这里不要简写啊！！

**Comment by tomoya92** [comment]
@TakWolf 下面有例子链接呀！

**Comment by TakWolf** [comment]
我的意思是不要写 t 写全 topic

**Comment by tomoya92** [comment]
@TakWolf 哦哦，懒了，没影响的吧！难道强迫证😁

**Comment by TakWolf** [comment]
题外话，朋也搜索的问题要去哪里反馈

**Comment by tomoya92** [comment]
@TakWolf 那个项目没开源，就在这下面说说吧！

**Comment by TakWolf** [comment]
搜索开放API吗

**Comment by tomoya92** [comment]
@TakWolf 没写，你需要的话，明天我加上就好了

**Comment by tomoya92** [comment]
@TakWolf 可以给cnode客户端加上搜索功能，挺好😃

**Comment by tomoya92** [comment]
@TakWolf 搜索api开发好了，就两个参数，不用我解释了吧！http://so.tomoya.cn/api/search?q=nodejs&site=cnode
site分别是，cnode, v2ex, ruby
期待cnode客户端加上搜索功能😊

**Comment by TakWolf** [comment]
pybbs api：

https://bbs.tomoya.cn/api/notification/count ，没有token会报500，
其他接口貌似有同样的问题

**Comment by TakWolf** [comment]
另外，返回结构中的 code 字段是模拟的 http status 吗？
（猜测可能是因为jfinal的返回限制）

**Comment by TakWolf** [comment]
搜索接口，希望能在提供一个联想词接口，（不是必要的）

**Comment by tomoya92** [comment]
就最后两个接口忘了加拦截器，已经修复

code是我自定义的一个类 Result，就三个属性 code, description, detail 统一返回格式的

pysearch里的提示是chrome做的，联想提示我没做这功能，昨天发现分页有点问题，还没来得及修复，有空了一块修一下

**Comment by TakWolf** [comment]
code 代码有文档吗？

**Comment by tomoya92** [comment]
@TakWolf code只有两个值，200正常201失败。失败对应有描述信息
