### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#12]
![image](https://cloud.githubusercontent.com/assets/6064962/17356573/d7ec1492-598a-11e6-91b8-a98a079a06b5.png)

**Comment by tomoya92** [comment]
我想起来了，你没有那么多权限，下面都没显示，就只显示了分割线了，我把他写在权限判断里就好了

**Comment by TakWolf** [comment]
发现已经修复，关闭了
