### ISSUE TITLE
调用图片验证码，注册一直通不过

### ISSUE THREAD

**Issue by alun1** [tomoya92/pybbs#123]
![BH5PJFT@KL8D~IKXZGMCE9X](https://user-images.githubusercontent.com/15731253/77843170-333b9a80-71cd-11ea-97b8-e6e5c4ddad11.png)

验证码图片的时候加了ver的

**Comment by tomoya92** [comment]
你请求头设置一下试试看  `Content-Type: "application/json"`

**Comment by alun1** [comment]
这个我已经知道了,因为我的demo没保存回话的cookie,为什么有的是 Content-Type: "application/json"  有的是application/x-www-form-urlencoded ,

**Comment by tomoya92** [comment]
接口里接收参数的类型不一样，这个你就按照文档来吧

**Comment by alun1** [comment]
> 接口里接收参数的类型不一样，这个你就按照文档来吧

好的

**Comment by tomoya92** [comment]
额外问下，大佬是在用flutter写app么？

开发好了，如果是开源的能否能个开源地址，如果不开源，能否给个下载地址？

我想在文档里做个宣传，谢谢

**Comment by alun1** [comment]
> 额外问下，大佬是在用flutter写app么？
> 
> 开发好了，如果是开源的能否能个开源地址，如果不开源，能否给个下载地址？
> 
> 我想在文档里做个宣传，谢谢

才开始,还要大佬多提携,如果上线肯定会通知你的
