### ISSUE TITLE
邮件发送失败，也可能是站长没有配置邮箱

### ISSUE THREAD

**Issue by linyuan805** [tomoya92/pybbs#124]
我注册了一个新用户，发话题时候显示邮箱未激活，然后去个人设置页面添加邮箱时候就会提示“邮件发送失败，也可能是站长没有配置邮箱”，但是我超级管理员已经设置了邮箱的密码，这是哪里的问题呢?

**Comment by tomoya92** [comment]
有可能是你配置的邮箱帐号或者密码错了，邮件没有发送成功
