### ISSUE TITLE
上传图片，一直报“请先登录”

### ISSUE THREAD

**Issue by alun1** [tomoya92/pybbs#127]
token传了，会话也有

**Comment by tomoya92** [comment]
感谢反馈，已经修复了

**Comment by alun1** [comment]
其实网页的上传没有问题,只是我的flutter客户端有问题,你直接其他地方会不会还是有问题,我主要想知道,少传了什么

**Comment by tomoya92** [comment]
没少传什么，web端的拦截器多配置了这个地址，所以就提示请先登录，这个接口走的是token校验，没必要在web拦截器中再校验一次

**Comment by alun1** [comment]
好的,谢了
