### ISSUE TITLE
关于日志

### ISSUE THREAD

**Issue by linkerlin** [tomoya92/pybbs#13]
代码里面有些 e.printStackTrace();
建议改成log。

**Comment by tomoya92** [comment]
如果有报错，直接输出，可以在tomcat日志里查看到，挺好的呀

**Comment by linkerlin** [comment]
(⊙o⊙)…  我以为你打算用log4j

**Comment by tomoya92** [comment]
@linkerlin 系统用的就是log4j 就算用log输出，jfinal里也有工具类LogKit
