### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by xubenjun1992** [tomoya92/pybbs#132]
Can static resources also be put into the project? CDN accelerated local cannot be accessed

**Comment by tomoya92** [comment]
太多了，懒得弄

你可以自己在github上下载release包，然后改一下代码即可。

**Comment by xubenjun1992** [comment]
不装了，说中文，下5.47版本是吧？然后直接使用这个/static/theme/default/js/codemirror.js不用自己再次编译生成.js文件了是这样吗

**Comment by tomoya92** [comment]
项目里用了好多的静态文件，你要下的不止codemirror这一个

全局搜一下 `<script` `<link`  把找到的cdn链接全都下载下来，放到static文件夹下，然后再把链接改一下即可

PS: 有些库是自带字体文件的，比如bootstrap, 如果你只下载一个bootstrap.css 它是找不到字体文件的，所以还是要去github上找人家打包好的release压缩包，然后再一个一个的解压到项目中

**Comment by xubenjun1992** [comment]
正在改codemirror，马上下bootstrap，先跑一下看看codemirror还报不报错
 <script src="/static/theme/default/js/codemirror.js"></script>
    <script src="/static/theme/default/libs/CodeMirror-5.47.0/mode/markdown/markdown.js"></script>
    <script src="/static/theme/default/libs/CodeMirror-5.47.0/addon/display/placeholder.js"></script>
