### ISSUE TITLE
关于分页

### ISSUE THREAD

**Issue by linkerlin** [tomoya92/pybbs#14]
首先，我觉得现在的分页实现的有些低效，尤其是帖子很多的情况。而且有limit，一定会在有并发修改的时候乱掉，比如取第二页之前有人发了新帖子。
第二，我觉得可以不用分页，做成，一次获取N条的类似Twitter的那种。对应sql是 
where  id> startid and id<=endid

**Comment by TakWolf** [comment]
帖子的排序规则是：最后回复时间（上浮功能），这不是一个稳定的排序规则，因此只要有并发存在，一定会乱序。

目前的规则：p = 当前页数，并发产生是，分页交界处会产生重复

楼主的规则：after = post.id ，通过锁定id获取后续，这样不会受到 index次序的问题，看似不会产生乱序问题，但是实际上有可能产生更大的问题，例如：边界处帖子被上浮，则有可能造成从头开始的大面积重复

**Comment by linkerlin** [comment]
只是会多一些或者少一些帖子而已吧？这个可以简单处理下。

**Comment by tomoya92** [comment]
其实我在想，要多少的并发才能造成分页大量重复？

一般逛论坛都是浏览，能发帖子的少之又少，所以我不认为会有什么问题

做成一次性查出来很多的帖子然后再做分页，这很少见吧！而且也比较麻烦，我就懒得弄了😂
