### ISSUE TITLE
系统提供了默认头像吗？

### ISSUE THREAD

**Issue by Noahhhhha** [tomoya92/pybbs#140]
您好，我使用 idea启动 和在 linux启动jar包 两种方式都试过，
系统好像没有提供用户默认头像是这样吗？
如果有，请问生成默认头像的代码在哪里。。。没找到。。。

**Comment by tomoya92** [comment]
跟踪一下注册的逻辑代码就能找到了 https://github.com/tomoya92/pybbs/blob/7bb9c34340ef5c7be5d0d643da88d5f0a6661f9d/src/main/java/co/yiiu/pybbs/service/impl/UserService.java#L94

**Comment by Noahhhhha** [comment]
万分感谢
