### ISSUE TITLE
用户注册后/api/user/{username}异常

### ISSUE THREAD

**Issue by wileySong** [tomoya92/pybbs#147]
用户注册（后台设置无需激活）点击用户名调用/api/user/{username}该接口，userService.selectByUsername(username)（用户获取失败，空指针）

**Comment by tomoya92** [comment]
能复现吗？

**Comment by wileySong** [comment]
能复现的，我是本地idea上启动的项目，每次新注册后点击用户名都会出现500错误，即上述接异常

**Comment by tomoya92** [comment]
我刚按照你的描述注册了两个用户都没有出现你说的那问题，你对master上的代码进行了什么改动吗？

**Comment by wileySong** [comment]
没改动，就是之前的user表没有email_notification这个字段，我手动加了一个text类型上去，其他没动，本地ES我没有配，应该跟这个无关吧

**Comment by tomoya92** [comment]
跟es没有关系，你把master代码重新clone一份，准备一个新的数据库，启动一下，再试试看，我没法重现也不知道是什么原因

**Comment by wileySong** [comment]
新注册的用户，在5分钟之内点击用户名，后台去根据名称查询用户信息失败，但数据库是有数据的，5分钟之后再点击用户名就没异常了，不知道是不是什么设置导致5分钟之内直接查询数据库是查询不到数据。

**Comment by tomoya92** [comment]
你是不是配置了redis缓存？把缓存去掉再试试看

**Comment by wileySong** [comment]
redis去掉了就好了，是不是要稍微优化下，加上redis就会出现上述异常。

**Comment by tomoya92** [comment]
修复了 https://github.com/tomoya92/pybbs/commit/80328eec976d32986d71f81ed1b6322e887f3a07
