### ISSUE TITLE
/api/upload异常

### ISSUE THREAD

**Issue by wileySong** [tomoya92/pybbs#148]
上传用户头像异常（用户头像第一次上传无异常，再次更新异常、token有时也刷新不成功）

file.transferTo(new File(localPath)); 异常

ERROR c.y.p.util.FileUtil - /Users/wileysong/IdeaProjects/pybbs/static/upload/avatar/wiley7/avatar.png

**Comment by tomoya92** [comment]
已修 https://github.com/tomoya92/pybbs/commit/9747022543be791ed4bb05c2b2ee83bb47582d61
