### ISSUE TITLE
关于商业使用

### ISSUE THREAD

**Issue by landuo** [tomoya92/pybbs#150]
如果想使用此项目作为商业产品（为公司搭建），请问需要授权吗？ 如何授权？

**Comment by tomoya92** [comment]
你好，

pybbs作为一个个人的开源项目，没有授权计划，但接受用户的捐赠

1. 捐赠超过**1000人民币**的话，项目作者在业余时间可提供**一周**的咨询服务
2. 捐赠超过**5000人民币**的话，项目作者在业余时间可提供**一个月**的咨询服务
3. 捐赠超过**10000人民币**的话，项目作者在业余时间可提供**三个月**的咨询服务
4. 捐赠超过**100000人民币**的话，项目作者在业余时间可提供**一年**的咨询服务

**捐赠数额高者优先解答咨询问题**

**所有捐赠者都会被记录在 [捐赠页面](https://github.com/tomoya92/pybbs/wiki/%E6%8D%90%E8%B5%A0)上**

捐赠方式可选择微信或者支付宝（捐赠完请加群联系群主，群号：1048094312）

![image](https://images.gitee.com/uploads/images/2021/0223/115428_99d1cc7f_82603.png) 
![image](https://images.gitee.com/uploads/images/2021/0223/115526_552f1c6a_82603.png)

**Comment by landuo** [comment]
十分感谢您的项目以及您的回复，谢谢！
