### ISSUE TITLE
楼主好，用docker-compose up -d 后报错了org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migration to version 1.5 (add sensitive word)

### ISSUE THREAD

**Issue by tenvin** [tomoya92/pybbs#151]
bbs-server | 2021-05-27 12:01:41 [restartedMain] INFO  o.s.c.s.PostProcessorRegi                                                                                                              strationDelegate$BeanPostProcessorChecker - Bean 'dataSourceConfig' of type [co.                                                                                                              yiiu.pybbs.config.DataSourceConfig$$EnhancerBySpringCGLIB$$24798464] is not elig                                                                                                              ible for getting processed by all BeanPostProcessors (for example: not eligible                                                                                                               for auto-proxying)
bbs-server | 2021-05-27 12:01:41 [restartedMain] INFO  c.z.h.HikariDataSource -                                                                                                               HikariPool-1 - Starting...
bbs-server | 2021-05-27 12:01:41 [restartedMain] INFO  c.z.h.HikariDataSource -                                                                                                               HikariPool-1 - Start completed.
bbs-server | 2021-05-27 12:01:41 [restartedMain] INFO  o.s.c.s.PostProcessorRegi                                                                                                              strationDelegate$BeanPostProcessorChecker - Bean 'dataSource' of type [com.zaxxe                                                                                                              r.hikari.HikariDataSource] is not eligible for getting processed by all BeanPost                                                                                                              Processors (for example: not eligible for auto-proxying)
bbs-server | 2021-05-27 12:01:41 [restartedMain] INFO  o.f.c.i.l.VersionPrinter                                                                                                               - Flyway Community Edition 5.2.1 by Boxfuse
bbs-server | 2021-05-27 12:01:41 [restartedMain] INFO  o.f.c.i.d.DatabaseFactory                                                                                                               - Database: jdbc:mysql://mysql:3306/pybbs (MySQL 5.7)
bbs-server | 2021-05-27 12:01:42 [restartedMain] INFO  c.z.h.HikariDataSource -                                                                                                               HikariPool-1 - Shutdown initiated...
bbs-server | 2021-05-27 12:01:42 [restartedMain] INFO  c.z.h.HikariDataSource -                                                                                                               HikariPool-1 - Shutdown completed.
bbs-server | 2021-05-27 12:01:42 [restartedMain] INFO  o.s.b.a.l.ConditionEvalua                                                                                                              tionReportLoggingListener -
bbs-server |
bbs-server | Error starting ApplicationContext. To display the conditions report                                                                                                               re-run your application with 'debug' enabled.
bbs-server | 2021-05-27 12:01:42 [restartedMain] ERROR o.s.b.SpringApplication -                                                                                                               Application run failed
bbs-server | org.springframework.beans.factory.BeanCreationException: Error crea                                                                                                              ting bean with name 'shiroConfig': Injection of resource dependencies failed; ne                                                                                                              sted exception is org.springframework.beans.factory.BeanCreationException: Error                                                                                                               creating bean with name 'myShiroRealm': Injection of resource dependencies fail                                                                                                              ed; nested exception is org.springframework.beans.factory.BeanCreationException:                                                                                                               Error creating bean with name 'adminUserService': Injection of resource depende                                                                                                              ncies failed; nested exception is org.springframework.beans.factory.UnsatisfiedD                                                                                                              ependencyException: Error creating bean with name 'adminUserMapper' defined in f                                                                                                              ile [/app/target/classes/co/yiiu/pybbs/mapper/AdminUserMapper.class]: Unsatisfie                                                                                                              d dependency expressed through bean property 'sqlSessionFactory'; nested excepti                                                                                                              on is org.springframework.beans.factory.BeanCreationException: Error creating be                                                                                                              an with name 'flywayConfig': Invocation of init method failed; nested exception                                                                                                               is org.flywaydb.core.api.FlywayException: Validate failed: Detected failed migra                                                                                                              tion to version 1.5 (add sensitive word)

**Comment by tomoya92** [comment]
你改代码了吗？

看起来像是数据源的问题，如果没动过代码的话，检查一下数据库连接信息配置的对不对

**Comment by xieYongGitHub** [comment]
@tenvin 请问你怎么解决了？

**Comment by atjiu** [comment]
把数据库删了重新运行。

发自我的iPhone
