### ISSUE TITLE
BBS启动后，后台一直报警告log

### ISSUE THREAD

**Issue by vip365** [tomoya92/pybbs#17]
BBS启动后，后台不停地报警告log，请问什么原因：

**log1：**
警告: The web application [bbs] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
十月 10, 2016 4:51:04 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
警告: The web application [bbs] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
十月 10, 2016 4:51:04 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [bbs] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)

**log2：**
[WARN]-[Thread: ContainerBackgroundProcessor[StandardEngine[Catalina]]]-[com.jfinal.plugin.ehcache.CacheKit.getOrAddCache()]: Could not find cache config [sysconfigcache], using default.

**Comment by tomoya92** [comment]
你这是jfinalbbs吧，第一个log我也不知道是什么原因，应该不影响使用
第二个log是因为ehcache.xml配置文件里没有配置sysconfigcache这个名称的缓存，jfinal就用ehcache的默认缓存了，这个不用管它

强烈推荐使用pybbs，jfinalbbs现在已经不维护了，感谢使用

**Comment by vip365** [comment]
我是下载的release版本的pybbs-jfinalbbs2.2，要下载master版本吗？

关于log，关键是一直报，这样部署也会影响性能。

**Comment by tomoya92** [comment]
@vip365 是的，master是最新版的。2.2分支是jfinalbbs最后一个版本

**Comment by vip365** [comment]
知道了，多谢。
