### ISSUE TITLE
目录分隔符替换报错

### ISSUE THREAD

**Issue by karlwanghn** [tomoya92/pybbs#19]
ClassSearcher.java 下
 private static List<String> findFiles(String baseDirName, String targetFileName)()方法 
fileName.substring(start + open.length(), end).replaceAll(File.separator, "."); 

报java.util.regex.PatternSyntaxException: Unexpected internal error near index 1  \错

**Comment by tomoya92** [comment]
你把 replaceAll 改成 replace 试试
