### ISSUE TITLE
Chrome下面输入框的问题

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#2]
chrome下面 textarea 默认状态是可以横向拉动的
![image](https://cloud.githubusercontent.com/assets/6064962/15743075/9a0e5204-28f5-11e6-9d72-33f86d4aed1f.png)
![image](https://cloud.githubusercontent.com/assets/6064962/15743085/a308982e-28f5-11e6-9212-29ed1bf57238.png)

**Comment by tomoya92** [comment]
这个属于用户自己操作导致页面布局的问题了，css里使用resize: none; 可以禁掉拉伸

社区用的是bootstrap的样式，对textarea没有重写样式，有强迫症的站长可以禁掉它，我就不去禁了^_^

**Comment by TakWolf** [comment]
应该设置为更合理
resize: vertical

**Comment by tomoya92** [comment]
哦哦，学习了，我回去看看效果咋样

**Comment by TakWolf** [comment]
另外输入框看不出支持Markdown，不知道的用户会懵逼

**Comment by tomoya92** [comment]
右边有提示说明，不过可以给输入框增加一个placeholder，回去我给加上

**Comment by TakWolf** [comment]
@tomoya92 解析@和棵体URL的逻辑在什么地方

**Comment by tomoya92** [comment]
@是在StrUtil.java里处理的，裸体url是marked.js里默认就可以解析的(我没记错的话)

**Comment by TakWolf** [comment]
我怎么感觉你这里写的不对啊，转移应该是`\\b`吧，你这样实际会匹配正斜杠的，你试一下

**Comment by tomoya92** [comment]
/b 是表示单词边界，这玩意可以解决@用户之后没有空格的问题
至于/b 与 \\b 我也纠结过，怎么写都不报错，我测试也没有出现问题，而且用户名里不会出现 / 这样的特殊字符吧

**Comment by TakWolf** [comment]
我实际测试的结果是这样的：
![image](https://cloud.githubusercontent.com/assets/6064962/15745352/f3cebce4-2903-11e6-881b-867b3fbed94d.png)
![image](https://cloud.githubusercontent.com/assets/6064962/15745361/fc9f27be-2903-11e6-99ce-27fbe5b60022.png)

而这样写会报错：
![image](https://cloud.githubusercontent.com/assets/6064962/15745380/1d7e50c2-2904-11e6-8ef4-282dcda8b240.png)

**Comment by tomoya92** [comment]
我测试结果

```
String str = "@tak/wolf1 @takwolf2@takwolf3 @takwolf4";
System.out.println(StrUtil.fetchUsers(str));

//输出
[tak/wolf1, takwolf3]
```

**Comment by tomoya92** [comment]
恩，我写的那个正则是对的

**Comment by TakWolf** [comment]
但是你的这个/b没起作用，最后一个显然没匹配

**Comment by tomoya92** [comment]
确实匹配不出来单词边界

**Comment by tomoya92** [comment]
其实也不用这样，at.js 默认会在后面加上一个空格，不是故意的话，是不会删除的，也就是可以匹配上
