### ISSUE TITLE
pom.xml 文件没对齐

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#20]
rt，强迫症受不了

-------- 分割线 -----------

Spring Boot 点赞！

**Comment by tomoya92** [comment]
已经对齐了，不知道为啥，我idea上好好的，提到github上就乱了

**Comment by TakWolf** [comment]
https://github.com/tomoya92/pybbs/blob/master/pom.xml#L28  这里顶上没有空格，
https://github.com/tomoya92/pybbs/blob/master/pom.xml#L109 而这里下面没有空格。

https://github.com/tomoya92/pybbs/blob/master/pom.xml#L132 这里则有两个空格！！

诶呀，我要死了 _(:з」∠)_

**Comment by tomoya92** [comment]
@TakWolf 。。。马上改一下

我也有强迫症，没你严重😂
