### ISSUE TITLE
主题抄一下这个站啊http://springcloud.cn/

### ISSUE THREAD

**Issue by vincentchen** [tomoya92/pybbs#21]
感觉那个专业

**Comment by TakWolf** [comment]
发现一个好网站

**Comment by tomoya92** [comment]
网站不错，后面有空的话，抄一下，谢谢建议

**Comment by vincentchen** [comment]
那个站使用的开源php论坛程序，应该比较好抄
https://github.com/flarum/flarum

**Comment by x-pengg** [comment]
这是一个PHP开源程序

**Comment by tomoya92** [comment]
@x-pengg 人家的意思是抄一下主题样式

**Comment by tomoya92** [comment]
又翻了一个这个站，已经换样子了，现在好像用的是wecenter（不确定），之前那个主题来自 https://github.com/flarum/flarum 这个开源项目，标记一下，有兴趣了，再加上这个主题
