### ISSUE TITLE
可否考虑移除 lombok ？

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#22]
这个东西虽然可以自动生成 getter 跟 setter，但是 编辑器啥的右键可以快速生成，没有感觉特别方便。bean如果不经常变动，getter跟setter也不需要经常动。

另外，这个东西依赖于编辑器，如果是自动化构建就会有问题

**Comment by tomoya92** [comment]
本来我是懒得写的getter，setter方法的，但你下面说到自动化构建有问题，这确实是个问题，一会我改下，提上去，谢谢提醒

**Comment by tomoya92** [comment]
@TakWolf 这个插件在自动化构建是没问题的，编辑器要装插件是为了开发不报错，真正编译的时候lombok会自动生成getter,setter

**Comment by gejun123456** [comment]
自动化构建不会有问题的，没必要移去，用lombok方便不少，至少加属性的时候不用再操作了。

**Comment by TakWolf** [comment]
我这里只能通过 idea 插件生成访问器，maven构建不会自动生成

**Comment by gejun123456** [comment]
你那边是代码编译不过吗，可以给个详细的截图吗
只要代码能编译过就没有问题

**Comment by tomoya92** [comment]
@TakWolf 这个。。反正也改过来了 😄 
@gejun123456 现在是有getter, setter的，编译是没问题的
