### ISSUE TITLE
可否考虑移除对 tomoya92/java-utils 的依赖

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#23]
https://github.com/tomoya92/java-utils

1.这个包你没有发布到中心厂库中
2.个人对这个库的一些实现持有保留意见
3.这个库是一个通用类工具库，而实际上项目中只用到一小部分工具
4.项目中用到的部分有更好的代替品
5.其他部分，作为项目级别的工具类似乎更合适

针对4，5详细说明：

## com.github.javautils.string.StringUtil.java

这个工具类，字符串相关的方法（isBlank,notBlank），跟 org.apache.commons.lang3.StringUtils 的实现是基本相同的
其他部分：
StringUtil.randomString(); // 产生一个随机字符串，这个应该是一个业务级别的逻辑，放在通用工具里面感觉不合理，应该放到项目基本的工具类中

StringUtil.fetchUsers(); // 查找@用户，同上

StringUtil.getUUID(): 这个函数的实现是这样的：
```
return UUID.randomUUID().toString().replaceAll("-", "");
```
UUID的标准格式中是有横线的，你去掉横线使用，跟上面的理由相同，这也是一个业务级别的逻辑
而且这里，你是作为文件名，我个人认为有横线没啥不妥的 

## com.github.javautils.encrypt.EncryptionUtil.java

这个命名存在问题，这里实现的实际上是编码，而不是加密
这里只用到了一个md5，可以被  Apache Commons Codec 代替

## com.github.javautils.net.IpUtil.java

只有一个方法是：getIpAddr()，根据 HttpServletRequest 取客户端ip地址，项目中用了记录日志
感觉应该作为项目级别的工具类

## com.github.javautils.web.CookieUtils.java

虽然import了这个类，但是其实根本没使用
另外这里Utils，而其他是Util，强迫症根本受不了啊

**Comment by Zeroman** [comment]
这个也要处理下，com.sun.image.codec.jpeg默认jdk 7和jdk8是编译不过的。还要特殊处理

**Comment by tomoya92** [comment]
是有些麻烦，发布了，好几个人都会卡在这个地方，可以考虑去掉这个依赖，我再整理一下
