### ISSUE TITLE
建议，吧 config.yml 合并到 application.yml

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#24]
spring boot 的哲学本身就是简化配置，统一配置，你把网站的配置独立出来没有啥特别的好处。
部署的时候，除了网站信息外，也要修改jdbc，导致同时要改两个文件。

application.yml 里面也不是只有spring节点，也有 log 这样作为根节点的，你添加一个自定义的 site 节点，感觉没啥问题

**Comment by tomoya92** [comment]
这个。。我也想呀，可不知道怎么写。。。然后就另外写一个配置文件了

**Comment by TakWolf** [comment]
https://github.com/tomoya92/pybbs/blob/master/src/main/java/cn/tomoya/common/config/SiteConfig.java#L12

这里如果不指定 locations，默认就是在 application.yml 里面查找

如果指定了，则独立出来

**Comment by tomoya92** [comment]
sure? 我试试看

**Comment by tomoya92** [comment]
果然是这样的，已经提交了

**Comment by TakWolf** [comment]
你的git到底有多少个提交名跟提交邮件

**Comment by tomoya92** [comment]
呃，公司一个，家里两个。。
