### ISSUE TITLE
包结构划分方式的讨论

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#26]
只是一个讨论，因为这个问题本身存在争议。

现有的包结构是安装功能模块划分的：

```
module
  collect
  index
  notification
  reply
  topic 
  user
```

每个模块通常包含四个包：

```
controller
dao
entity
service
```

目前这么分包存在的问题：
1.包结构特别多，但是很多包其实只有一个类，比如：module.user.service.UserService.java 只有这一个类
2.命名冗余，例如 module.user.service.UserService.java ，他本身就存在于 Module.user 包，那么 UserService 前面的User是不是冗余的？
3.依赖结构应该是内聚的，例如 UserService 应该是一个用户相关的业务类，但是其实跟用户相关的模块，例如 topic，notification都会用到，这些跟user模块是平行关系，但是却是互相依赖。所以UserService是不是应该是高于module的结构？
4.有一些类没地方放，例如 BaseController，BaseEntity被放到了common包里，Result其实应该属于entity（尽管他不是一个domain），现在只能放到 util 里面的。
5.无法纵向分层。举个例子，很多网站是这样部署的：
bbs.tomoya.com -> 网站端
api.tomoya.com -> Api端
这两个跑在独立的端口，是两套程序，这样的结构很常见。
假如我现在有了这样的需求，想要对pybbs做改造，可能的改造思路是：
把现有的项目拆分成三个子项目，分别是：
core  -> 包含 entity，dao，service
web -> 依赖于core，包含 webController，webService，是个可执行程序
api -> 依赖于core，包含 ApiController, apiService，是个可执行程序
未来可能构造一个聊天室 chat.tomoya.com -> 依赖于 core 核心业务区扩展就行了
现有的分包模式很难做这样的改造，因为无法提取core

----------- 分割 --------------

结构应该是自顶向下的：
Controller
依赖于
Service
依赖于
Domain

对于底部的是依赖关系，而对于顶部的则完全不可知

----------- 分割 --------------

按照上面的理由，更合理的一种方式可能是安层分或者按照类功能分：

```
config
controller
   web
      IndexController.java
   api
      UserApiController.java
service
domain
   entity
   dao
util
```

我最早也是按照module分包，经过实践目前倾向于按照层分包。
当然这个问题本身也存在争议，社区也有广泛的讨论。

这个issues只是一个讨论，不一定是一个建议。目的是希望可以找到一个最佳实践。

**Comment by tomoya92** [comment]
看到这个我一时还真不知道该怎么回复了，下面说说我的想法

> 包结构特别多

其实这个问题完全是出于个人的开发习惯，我现在这样分的包，虽然在有很多包里只有一个类，但找相关的代码会非常方便，对新手很友好

如果将包分成 controller dao entity service 这么几个，那样项目大了之后，我觉得会很乱，还有一个原因是我不放一块的，比如

pybbs里有一个security的包，它里面就不止有 controller dao entity service 这么四个，还有一个core包，我用来放spring security相关的类文件，这样一看，每一个module下都有可能会产生出其它的东西，这样也就体现了按module分包的好处了

----

> 命名冗余

现在的命名完全就是为了ide能快速的找到类而命名的，如果module下的包里的controller都叫controller.java，那用ide快速找类就很痛苦了

----

> 依赖结构应该是内聚的

打个比方，module就是一个国家，module下的user, topic ... 都是一个一个的家庭，家庭与家庭之间会存在亲戚关系，就好比是它们的依赖关系，你能说这个家庭里的某个成员要脱离module(国家)而存在吗？只是个比方，见笑了~~

-----

> 有一些类没地方放

这个确实是个问题，不过它们本来就是某些包下（controller，entity）的公共类，放到common里也勉强说得过去😂

----

> 无法纵向分层

这个问题我赞同你的想法，不过你这里说的分模块应该不是基于包名的 module/xxx 这样的模块的意思，而是相当于新建一个module(idea里的说法)来当模块对吧，后面我弄清楚了，会考虑这个分法

--- 

以上

**Comment by heikehuan** [comment]
比较赞成现在的包和类结构，我个人以前做过的大项目，都是按业务划分包结构，叶子包底下都有controller, service, util, domain 这几个基本结构。这样业务再庞大，也能很快分得清子集和父集关系。
不过有些地方需要微调，权限这种东西，应该是通用的，放在common比较好。
我认为的common，应该是业务上，整个系统公用的，包括工具类和user处理，权限处理。

**Comment by x-pengg** [comment]
其实我觉得可以改为 Maven 的 Module 结构

**Comment by blackshow** [comment]
按moudle分比较方便拆分成子moudle,至于报下面有几个类，都用IDE，其实无所谓吧，基本也不会用鼠标去点
