### ISSUE TITLE
缺少配置文件src/main/resources/config.yml

### ISSUE THREAD

**Issue by arisoyang** [tomoya92/pybbs#29]
readme里面有一句：修改配置文件 `src/main/resources/application.yml` `src/main/resources/config.yml` 里的配置项

可是我没有找到啊！

**Comment by arisoyang** [comment]
在群里面得到了 【宗师】冈崎的及时帮助。问题得以解决。实际上config.yml合并到application.yml里面了。

请关闭这个issue.

**Comment by tomoya92** [comment]
config.yml跟application.yml合并了，readme忘了更新
