### ISSUE TITLE
关于许可证

### ISSUE THREAD

**Issue by TakWolf** [tomoya92/pybbs#3]
项目使用MIT授权，但是商用却需要许可

**Comment by tomoya92** [comment]
开源协议一直不太明白，MIT协议应该是最宽松的协议了，但又不想被商用

开源，但不允许商用应该用啥协议呀？

**Comment by TakWolf** [comment]
你期望的商用定义是什么的？

例如：假如我现在拿来做商用论坛，需要付费吗

**Comment by tomoya92** [comment]
是的

例如：假如我现在拿来做商用论坛，需要付费吗

就是这个意思

**Comment by TakWolf** [comment]
我现在对项目产生分支，并自主衍生，协议继承了MIT，但是没有使用，需要付费吗？

别人使用了我衍生的分支，继承了MIT协议，需要联系原项目作者付费吗？

**Comment by TakWolf** [comment]
另外，使用都算商用吗？还是说使用产生盈利才算商用？

例子1：我是买手机的，我靠手机赚钱，我搞了个用户论坛，免费注册，这算商用吗？
例子2：我是做资源论坛网站的，注册需要购买邀请码，下载需要付费，这算商用吗？

**Comment by tomoya92** [comment]
好麻烦，，这样说的话，在衍生分支的时候就要通过开源协议限制了

我的想法就是个人使用，想怎么使用都可以，但商用就要购买版权了，不管商家从那得来的代码（只要是来自pybbs，就要购买版权）

**Comment by tomoya92** [comment]
例子1：我是买手机的，我靠手机赚钱，我搞了个用户论坛，免费注册，这算商用吗？
例子2：我是做资源论坛网站的，注册需要购买邀请码，下载需要付费，这算商用吗？

这个我感觉已经分不清了，有什么好的办法解决吗？

**Comment by TakWolf** [comment]
你去搜索一下AGPL看看是不是满足你的条件

另外，去看一下Qt的授权模式 https://www.qt.io

**Comment by TakWolf** [comment]
冲突主要在于，MIT是可以闭源免费使用的，但是你要求商用授权，这个MIT协议就没有任何意义了。

**Comment by tomoya92** [comment]
AGPL协议挺好，谢谢，我改下协议

**Comment by TakWolf** [comment]
额外的讨论，我记得早期是技术支持付费的，自由赞助，那样不是挺好的吗？

目前的授权方式，不是很舒服。

**Comment by tomoya92** [comment]
对了，还有技术支持付费的方式，，，我还是改回来算了，懒得在这上面纠结太多，太纠结了，这个。。

不过对于开源协议倒是清晰了很多，谢谢你
