### ISSUE TITLE
上传图片问题

### ISSUE THREAD

**Issue by LiHaoGit** [tomoya92/pybbs#30]
我使用markdown编辑器,上传图片成功后,访问图片是404,必须要重新再部署一遍,才能显示图片

spring boot 2.4版

**Comment by tomoya92** [comment]
你是用main方法启动的对吧，上传是传到static目录下的，main方法启动没有热加载，就会出现这个问题，但如果部署在tomcat里的话，或者用nginx做静态文件映射也是没有问题的

**Comment by TakWolf** [comment]
图片服务为什么不做成第三方cdn的形式

**Comment by LiHaoGit** [comment]
@tomoya92 
我用的是tomcat启动的,也会有这个问题
![qq 20161206105359](https://cloud.githubusercontent.com/assets/7036191/20911353/5b777db4-bba2-11e6-95e0-705d12fdfe70.png)
@TakWolf 
cdn是可以的,只是碰到了这个问题,所以想看下究竟是什么原因

**Comment by tomoya92** [comment]
![image](https://cloud.githubusercontent.com/assets/6915570/20911416/bfc8cfa2-bba2-11e6-88d4-1edd945a5f1b.png)
你上传文件之后先把窗口焦点切到idea，什么都不做，然后再切到浏览器上，刷新应该就有了，其实还是要部署一下，只不过tomcat会自动的部署，main方法启动不会
