### ISSUE TITLE
注解错误

### ISSUE THREAD

**Issue by LiHaoGit** [tomoya92/pybbs#36]
[src/main/java/cn/tomoya/module/topic/controller/TopicController.java](https://github.com/tomoya92/pybbs/blob/master/src/main/java/cn/tomoya/module/topic/controller/TopicController.java#L94)
应该为 `@GetMapping("/{id}/edit")`

**Comment by tomoya92** [comment]
这个估计是改漏掉的，不影响使用，@RequestMapper默认就是Get请求，下次更新我改了提掉

**Comment by tomoya92** [comment]
已经改好了
