### ISSUE TITLE
咱做的东西能不能用点心

### ISSUE THREAD

**Issue by vip365** [tomoya92/pybbs#4]
咱做的东西能不能用点心，有bug不要紧，咱可以完善，起码系统能启动啊，别人用你的东西，从数据库到工程全都得调一遍，不然全是错。你做的东西，分享出来，大家用的同时帮你完善，如果不能用那不就白费了吗？

**Comment by tomoya92** [comment]
不知道你运行的时候报什么错，能发出来吗？

在readme.md里我写的也有怎么开始，按照上面的来，一步一步的没问题的呀！

**Comment by TakWolf** [comment]
@vip365 楼主你好，有问题请直接说问题，请不要上来就先喷一顿。

你把错误发出来，大家看看到底是谁的问题。

为啥我部署咋就没问题呢？

**Comment by xbitlabs** [comment]
超级管理怎么登陆？有管理后台？

**Comment by tomoya92** [comment]
@xbitlabs 没有管理后台，没有本地登录，都是第三方登录，目前支持了github，新浪微博的授权登录

如果想本地调试可以看看这个话题进行配置： http://bbs.tomoya.cn/t/17 

如果是发布到服务器上去进行访问，可以看看这两篇话题进行配置：http://bbs.tomoya.cn/t/26 http://bbs.tomoya.cn/t/27 

如果超级管理配置不好，可以看看 readme.md 里关于权限的说明，或者直接查看话题：http://bbs.tomoya.cn/t/25

** 建议到 bbs.tomoya.cn 上去看看现有的话题，一般需要注意的，需要配置的，我都发布话题进行说明了，还是有问题可以提issues，或者在网站里发问答 **

**Comment by tcrow** [comment]
感谢分享
