### ISSUE TITLE
登录偶尔会出现 403

### ISSUE THREAD

**Issue by x-pengg** [tomoya92/pybbs#40]
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Dec 29 18:02:41 CST 2016
There was an unexpected error (type=Forbidden, status=403).
Invalid CSRF Token '48dcca5a-1458-42f0-94e3-5cd6cb398fea' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'.

**Comment by tomoya92** [comment]
能说一下重现步骤吗？

**Comment by x-pengg** [comment]
@tomoya92 重现不了，这个问题是偶尔会出现的。

**Comment by tomoya92** [comment]
我还没有碰到过，先放这吧，你啥时候发现重现步骤了，来这记一笔
