### ISSUE TITLE
级联删除的问题

### ISSUE THREAD

**Issue by samforit** [tomoya92/pybbs#47]
首先应该赞扬您这种开源奉献的精神。  
我看到代码中有这样的使用示例
``` 
deleteTopic(int topicId){
deleteReplyByTopicId(topicId);
deleteTopicById(topicId);
}
```
我觉得，如果要用hibernate，就应该用上级联删除相关的功能，因为只需要在entity中指定对应的级联关系即可。  
如上这段代码，就忘了级联删除对应的collect，如果某个topic被收藏了，那么删除topic的时候肯定会报出外键关联异常。  
或者说，整个项目就不要设置各个entity之间的关联关系，不使用数据库外键。

**Comment by tomoya92** [comment]
这个我知道, 所以我把user的删除给去掉了, 删除一个用户好烦, 如果不用关联关系, 开发又太麻烦了, 所以现在也没什么好的解决办法, 只能发现一个解决一个了

**Comment by tomoya92** [comment]
已经修复了, 感谢提醒
