### ISSUE TITLE
emoji表情编码插入数据库出错

### ISSUE THREAD

**Issue by LaudOak** [tomoya92/pybbs#48]
输入内容包括emoji表情时,比如😄,会抛出异常
 java.sql.SQLException: Incorrect string value: '\xF0\x9F\x98\x84'
可以参考[https://mathiasbynens.be/notes/mysql-utf8mb4](https://mathiasbynens.be/notes/mysql-utf8mb4)解决一下

**Comment by tomoya92** [comment]
这个把数据库的字符集改一下就可以了，用utf8mb4

**Comment by LaudOak** [comment]
@tomoya92 换字符集需要把数据库,表,列的字符集都换掉吧

**Comment by tomoya92** [comment]
@LaudOak 我记得是创建数据库的时候选一下就可以了的，你试试吧

**Comment by tomoya92** [comment]
@LaudOak 这个我有空了，改一下

**Comment by LaudOak** [comment]
@tomoya92 好

**Comment by beldon** [comment]
我在写微信公众号开发的时候也出现过同样的问题，如朋也所说，把数据库字符集改为utf8mb4，这里有一篇教程，可以参考参考[mysql/Java服务端对emoji的支持](http://blog.csdn.net/u013628152/article/details/46776987)

**Comment by tomoya92** [comment]
@beldon 我好像就是看的这篇文章改的 😂
