### ISSUE TITLE
一个交流

### ISSUE THREAD

**Issue by maosjz** [tomoya92/pybbs#5]
失业中，打算做个完整的符合自己业务的BBS，请问作者可否提供一些技术支持。

**Comment by tomoya92** [comment]
楼主会编程吗？如果会的话，可以自己按照readme.md里的说明来自己搭建bbs，有什么不懂的，可以在bbs.tomoya.cn里发问答。

如果不会编程还需要技术支持，就需要付费了哦！

**Comment by maosjz** [comment]
主要是有两个问题，一：工作量太大，
二：也是涉及到的最大问题，我想去掉所有开源相关的信息，以免被人分析出漏洞，我打算商用。

**Comment by tomoya92** [comment]
这个，估计改动就太大了，路由，参数都要改了，你好好想想吧

**Comment by maosjz** [comment]
如果你们代为开发，以多少价位一个人月？去掉开源相关的信息，需要你们的授权书。

**Comment by tomoya92** [comment]
如果按照你说的来改的话。那跟重新写一个BBS没有两样。而且后续如果有更新的话。你不还得找人帮你改吗？

**Comment by tomoya92** [comment]
如果你担心社区不安全。欢迎到线地址去找漏洞
