### ISSUE TITLE
【问题】以打jar包的形式部署的话，如何处理更新问题？ jar包运行日志在哪里？

### ISSUE THREAD

**Issue by JsonHive** [tomoya92/pybbs#52]
如果以jar包部署，那么需要更新的时候是要替换整个jar包么？能做到不停机更新么？

还有就是jar包启动日志跑哪去了，找了半天没找到？

**Comment by tomoya92** [comment]
@JsonHive java你能做到不停机重启服务吗？你要有好用的方法可以告诉我一下，有更新是需要整个替换的，后台启动用的是nohup，日志的话你可以去看一下这个命令相关的介绍。

**Comment by JsonHive** [comment]
我的意思是如果只更新一些前台样式，是没必要停机的

**Comment by tomoya92** [comment]
@JsonHive

**Comment by JsonHive** [comment]
你没理解我的意思，举个例子：论坛有一个按钮的样式出现问题，错位了，我调整好css样式后，正常替换css文件，样式就能自动变更。 但是如果以jar包运行，是需要替换整个jar包的

**Comment by tomoya92** [comment]
@JsonHive 是你没理解我的意思，css是不是静态文件？截图里的第二种方法不就是告诉你怎么做静态资源映射吗？明白了吗？

**Comment by JsonHive** [comment]
这样，那我明白了

**Comment by JsonHive** [comment]
还有就是日志的问题，这个必要严重，我觉得不应该使用nohup记录的结果去作为日志分析记录的，我看你代码里有 log的记录，仍然需要像log4j等工具管理日志，方便日后排错，以及日志分析

**Comment by JsonHive** [comment]
我知道，但日志分析不能以nohup的记录作为分析，他会把你控制台所有的内容记录出来，你仍然需要将info，warn，error日志信息格式化，并且分离开方便你排错，以及日志分析

**Comment by JsonHive** [comment]
重点不是在这，我觉着日志的管理应该是自动，不需要管理员手动参与

**Comment by tomoya92** [comment]
@JsonHive 我觉得nohup的日志跟tomcat里的log/catalina.out是一样的，要做日志分析可以在代码里把要分析的地方日志用log4j或者其它东西打出来，自己统一好，就可以了，如果对这个不满意的话，也可以自己打war包，或者自己编译好，上传到tomcat里运行

**Comment by JsonHive** [comment]
嗯，明白了
