### ISSUE TITLE
如何把application.yml放到打包好的jar包外面配置？？

### ISSUE THREAD

**Issue by haoning7788** [tomoya92/pybbs#53]
我用maven打包了工程得到jar包，但我想直接修改jar包里的配置文件，配置域名等等，所以就解压了jar包配置完了然后再压缩，但发现jar包损坏没法运行了，所以想把配置文件放到jar包外面，请问大神这个该如何解决？

**Comment by tomoya92** [comment]
https://github.com/tomoya92/pybbs/wiki

**Comment by haoning7788** [comment]
感谢感谢大神

**Comment by haoning7788** [comment]
@tomoya92 那个再问下大神，我用maven打包一个jar包，然后解压开想修改前端的文件，这个怎么做到？

**Comment by tomoya92** [comment]
https://github.com/tomoya92/pybbs/wiki/jar%E5%8C%85%E8%BF%90%E8%A1%8C&%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE

**Comment by haoning7788** [comment]
太厉害了，太友好了，太感谢你了
