### ISSUE TITLE
Springboot版本启动后后台主页无法访问

### ISSUE THREAD

**Issue by zhouplus** [tomoya92/pybbs#54]
admin/index路径无法访问。前台页面访问正常。

**Comment by tomoya92** [comment]
@zhouplus 是不是没权限？

**Comment by zhouplus** [comment]
我就是从git上clone下来的啊，正常也应该跳转到登陆页面吧。

**Comment by tomoya92** [comment]
@zhouplus 按照readme写法，把权限sql导入数据库，用我给定的帐号登录再试试

**Comment by zhouplus** [comment]
首先谢谢解答。这次登陆进入了，但是不知道对不对，和以前不太一样，我以前用过之前的jfinalbbs.揭秘那风格不一样，进入后修改权限也没有找到保存的地方，在右上角点击进入后台，后台样式和前台一样。不知道这是不是正常。

**Comment by tomoya92** [comment]
@zhouplus 以前是带后台的，后台主题用的是adminlte，现在前台后台都合并了，没有后台了，界面用的都是bootstrap

修改权限下面有个确定按钮
