### ISSUE TITLE
导入 pybbs.sql 出错

### ISSUE THREAD

**Issue by feitian124** [tomoya92/pybbs#59]
我命令行导入 pybbs.sql 出错了。。
mysql> source /home/develop/learn/pybbs/pybbs.sql
ERROR 1366 (HY000): Incorrect string value: '\xE4\xBB\xAA\xE8\xA1\xA8...' for column 'description' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xE8\xB6\x85\xE7\xBA\xA7...' for column 'description' at row 1
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`pybbs`.`pybbs_role_permission`, CONSTRAINT `FKksb0b8rm0k0b89trps3dd0doj` FOREIGN KEY (`role_id`) REFERENCES `pybbs_role` (`id`))
ERROR 1366 (HY000): Incorrect string value: '\xE5\x88\x86\xE4\xBA\xAB' for column 'name' at row 1
ERROR 1048 (23000): Column 'block' cannot be null
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`pybbs`.`pybbs_user_role`, CONSTRAINT `FKd8byynux0fguwt59me1kc9fbj` FOREIGN KEY (`role_id`) REFERENCES `pybbs_role` (`id`))

**Comment by tomoya92** [comment]
@feitian124 这是emoji支持问题，请对着 https://tomoya92.github.io/pybbs/question/ 里的说明处理一下让数据库支持emoji就可以了，如果不想设置支持emoji，可以把pybbs.sql里的emoji删除再导入即可

**Comment by feitian124** [comment]
谢谢。
我的问题好像是应该先运行   
mysql> source /home/develop/learn/pybbs/pybbs-table-structure.sql
再运行
mysql> source /home/develop/learn/pybbs/pybbs.sql

我再看看你说的  emoji 问题

**Comment by tomoya92** [comment]
@feitian124 pybbs启动后是自动创建表的，pybbs-table-structure.sql文件是给升级用户对比表结构用的，不是创建表结构的，请以程序自动创建的表为准

**Comment by feitian124** [comment]
谢谢，已经解决。
不过不知道发帖的时候咋用 emoje，ruby-china 输入 ：后貌似会自动弹出emoji 待选。

**Comment by tomoya92** [comment]
@feitian124 哦，pybbs里的编辑器还没有集成emoji，你要想输入，只能用输入法自带的或者到 getemoji.com 上去复制

**Comment by feitian124** [comment]
哦，谢谢。那可以考虑先默认禁用 emoji 吧，对新关注的人更友好点。有兴趣的再依照步骤自行开启。

**Comment by tomoya92** [comment]
@feitian124 这个方便，把pybbs.sql里的那个emoji删除即可

**Comment by tomoya92** [comment]
@feitian124 你用的pybbs.sql里有emoji吗？我看了下，master分支里的sql文件是没有emoji的呀

**Comment by feitian124** [comment]
哦，那可能是我没更新。刚才更新了代码，也设置了 mysql 字符集，不记得先做的哪个了。
目测没有了
