### ISSUE TITLE
是不是可以考虑下支持简单的静态化？

### ISSUE THREAD

**Issue by linkerlin** [tomoya92/pybbs#6]
或者页面可以直接导出一个pdf?
这样子对搜索引擎比较友好。

**Comment by tomoya92** [comment]
pybbs页面都是在后台渲染的，没有用到js渲染，这样对搜索引擎已经挺好了，不知道你说的导出pdf是什么意思，我对seo也不是太懂

**Comment by linkerlin** [comment]
我说的导出pdf，就是在每个页面上提供一个导出pdf的链接。
这样子，搜索引擎会搜索对应的pdf，从而加重权重。

**Comment by tomoya92** [comment]
没见过哪个论坛有这功能吧，网站权重不在pybbs的开发范围，谢谢你的建议

**Comment by linkerlin** [comment]
ok。
是不是可以考虑RSS呢？

**Comment by tomoya92** [comment]
RSS倒是可以加上，不过也是非必须的功能，什么时候想加的话，在加吧
