### ISSUE TITLE
服务容易假死

### ISSUE THREAD

**Issue by jinshui1982** [tomoya92/pybbs#60]
在TOMCAT中跑一天后，服务就容易假死，不知道是啥原因。

**Comment by tomoya92** [comment]
你用的什么版本？spring-boot版本不是用tomcat启动的了

**Comment by jinshui1982** [comment]
用的jfinal版本，打包部署的。

**Comment by tomoya92** [comment]
你看看你的是不是这个问题导致的 https://github.com/tomoya92/pybbs/issues/51

**Comment by jinshui1982** [comment]
好像是这个问题。我把定时任务修改为1分钟执行一次，20分钟后就出现服务假死的情况。

但不知如何修改。指导一下？

**Comment by tomoya92** [comment]
@jinshui1982 在定时器执行完了，就把redis的连接关了，应该有关闭的方法，你找找看

**Comment by jinshui1982** [comment]
关闭掉还是会出现。

/**
 * Created by tomoya.
 * Copyright (c) 2016, All Rights Reserved.
 * http://tomoya.cn
 */
public class ClearCacheJob implements Runnable {
    @Override
    public void run() {
        LogKit.info("开始清理缓存");
        Cache cache = Redis.use();
        cache.getJedis().flushDB();
        cache.close(cache.getJedis());
        if(cache.getJedis().isConnected()){
        	cache.getJedis().close();
        }
        LogKit.info("缓存清理完成");
    }
}

**Comment by tomoya92** [comment]
@jinshui1982 那我就不太清楚了，你可以去jfinal官网上去问问看，
不过推荐你用spring-boot版本的pybbs，这个是一直维护下去的，
另外方便告知一下你部署pybbs的域名吗？我加到readme里，谢谢！

**Comment by jinshui1982** [comment]
不好意思，现在部署在内网，没部署公网。

我再解决一下。有方案了共享给您。

谢谢。

**Comment by tomoya92** [comment]
@jinshui1982 好的，谢谢
