### ISSUE TITLE
话题收藏问题 

### ISSUE THREAD

**Issue by mazhiyuan123** [tomoya92/pybbs#65]
加入或者取消收藏 页面刷新了 实际上页面没有看见变化
比如加入收藏 页面刷新应该变成取消收藏
取消收藏反之
也同样造成了可以多次加入收藏 这样就出现了另外一个问题 同一用户加入收藏之后 在刷新页面 就500了

**Comment by tomoya92** [comment]
这个是缓存的问题，而且程序里也对多次收藏做判断了，估计还是缓存的原因才导致会重复收藏的

**Comment by tomoya92** [comment]
去掉缓存就好了
