### ISSUE TITLE
为什么js会被篡改

### ISSUE THREAD

**Issue by githubzy** [tomoya92/pybbs#66]
请问为什么js会被篡改

**Comment by TakWolf** [comment]
哪里的js被篡改？

**Comment by githubzy** [comment]
自定义的js都被篡改了

**Comment by tomoya92** [comment]
@githubzy 请描述详细点，怎么能重现它？

**Comment by githubzy** [comment]
首先对作者表示敬意
^-^
我也是刚发现，之前没有出现过这种情况，我发布出来后，突然页面访问异常，多了广告的信息，然后数据也不显示。然后发现凡是我定义的js全部被篡改。

**Comment by tomoya92** [comment]
@githubzy 那你方便把你自己定的js贴出来吗？还有在页面里引用的代码贴出来吗？

**Comment by TakWolf** [comment]
部署在什么服务器上。
访问网络是什么？

先确定是不是线路被劫持。

**Comment by githubzy** [comment]
谢谢二位
代码不能贴出来，实在是抱歉
我这边先确定下是不是被劫持了，有问题再提issue
十分感谢
