### ISSUE TITLE
两个版本都在同时发展吗？

### ISSUE THREAD

**Issue by fandasoft** [tomoya92/pybbs#69]
@tomoya92 首先谢谢朋也提供了这么好一个软件！ 虽然也有基于nodejs的做得不错的社区软件，但是感觉还是Java+MySQL的更加亲切😊

想采用，但是现在有两个版本，一个是pybbs，一个是YIIU， 好像都在更新，我该如何选择呢？
我想使用MySQL数据库，搜索引擎用Solr，此外编辑器我看了YIIU好像是MD的，pybbs的截图显示采用的编辑器是传统的，我可能更倾向于传统的。

另外，不知道是否有上传附件的功能？

谢谢！

**Comment by tomoya92** [comment]
现在pybbs已经转移到yiiu-co组织里了，维护也只是yiiu这一个了，pybbs不再进行维护了

上传附件功能没有
