### ISSUE TITLE
注册用户失败问题 希望加入readme

### ISSUE THREAD

**Issue by Mesteruser** [tomoya92/pybbs#70]
在register.ftl中
 $.ajax({
        url: 'api/register',
        async: false,
        cache: false,
        type: "post",
        dataType: "json",
        data: {
          username: $("#username").val(),
          password: $("#password").val(),
          email: $("#email").val(),
          emailCode: $("#emailCode").val(),
          code: $("#code").val()
        },
原文件url 没有api/

**Comment by tomoya92** [comment]
你应该发错项目了，这个项目里没有这个问题，而且这个项目也不维护了，你说的应该是yiiu里的问题，今天已经修改提交了
