### ISSUE TITLE
在windows开发启动时，会因为mysql连接时区设置报错No timezone mapping entry for 'GMT 8"

### ISSUE THREAD

**Issue by godzoco** [tomoya92/pybbs#80]
是jdbc连接mysql时区设置问题在文件application-dev.yml 中修改为
datasource_driver: com.mysql.cj.jdbc.Driver
datasource_url: jdbc:mysql://localhost:3306/pybbs?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
datasource_username: root
datasource_password: 123456

即可正常使用

**Comment by tomoya92** [comment]
感谢，已整合进文档常见问题里了
