### ISSUE TITLE
使用

### ISSUE THREAD

**Issue by cherryxyz** [tomoya92/pybbs#83]
hi 大佬，我是公司一个java菜鸟，或者说唯一一个懂一点java开发的人员。现在领导交给我一个任务开发一个供公司内网使用的BBS论坛，我在github上搜了一下，你这个文档比较全一点，所以打算使用你这个。后续应该会有很多问题想要请教，能否帮忙解答。谢谢！

**Comment by tomoya92** [comment]
你能碰到的问题, 基本上在文档里都能找到说明, 仔细看文档就可以了

当然如果文档里实在没找到的话, 可以问我
