### ISSUE TITLE
日期控件不支持时分秒和中文？

### ISSUE THREAD

**Issue by Liuguozhu** [tomoya92/pybbs#86]
![image](https://user-images.githubusercontent.com/13363055/58316937-51b36580-7e47-11e9-8f8a-4c2aaa55a27e.png)
![image](https://user-images.githubusercontent.com/13363055/58317089-a7880d80-7e47-11e9-99d6-00c5f573613a.png)

`        $("#publishTime").datepicker({
          autoclose: true,
          format: 'yyyy-mm-dd hh:ii:ss',
          language : 'zh-CN',
          minuteStep:1,
          todayBtn: true,
          todayHighlight: true,
        });`

**Comment by tomoya92** [comment]
没有让它支持时分秒, 因为加上时分秒太麻烦了,

中文这个我当初开发的时候指定语言它不生效, 也就没有弄了..

**Comment by Liuguozhu** [comment]
点Today按钮也没反应，不会自动填充当前日期。好吧，那我看着弄吧。

**Comment by tomoya92** [comment]
@Liuguozhu 日期选择中文加上了， 多引了一个js

至于 today 按钮， 它的功能是当你翻到其它时间去的时候， 点一下today会回到今天这个日期的界面， 你可以试一下

自动填充我觉得没有必要加上， 本来就是要用户自己选的， 如果上来就自动填充， 就没办法搜索全部时间的内容了

**Comment by Liuguozhu** [comment]
我已经换成了datetimepicker了:smile:

**Comment by Liuguozhu** [comment]
![image](https://user-images.githubusercontent.com/13363055/58366307-f050cc80-7f02-11e9-90de-dd00607e5703.png)
