### ISSUE TITLE
图片访问路径问题

### ISSUE THREAD

**Issue by NiuJunzhe** [tomoya92/pybbs#87]
后台无报错，头像无法显示

**Comment by NiuJunzhe** [comment]
GET http://localhost:8080/static/upload/Anxunze/avatar.jpeg?v=5 404 (Not Found)

**Comment by Liuguozhu** [comment]
这个是你没配置图片路径，请先登录后台(后台地址：http://localhost:8080/adminlogin   账号密码自己看readme)
在这里配置一下路径就可以了
![image](https://user-images.githubusercontent.com/13363055/58367200-f0ef6000-7f0e-11e9-80d2-9053c33c5740.png)

**Comment by NiuJunzhe** [comment]
是配置完成后还没有显示，最后重启redis就好了，谢谢啦
