### ISSUE TITLE
服务跑一段时间会挂掉

### ISSUE THREAD

**Issue by Liuguozhu** [tomoya92/pybbs#88]
挂之前日志如下：
![image](https://user-images.githubusercontent.com/13363055/58770529-0be26400-85e2-11e9-9e2f-14005e8eda67.png)
目前给idea加了参数（不知道会不会起作用）：
-XX:CompileCommand=exclude,org.eclipse.jdt.internal.compiler.parser.TypeConverter::*

**Comment by tomoya92** [comment]
@Liuguozhu 请问你的jdk版本跟jre版本一样吗？

如果版本一致还报这个错，在启动命令后加上这个参数  `-XX:+CreateMinidumpOnCrash` 再试试

**Comment by Liuguozhu** [comment]
![image](https://user-images.githubusercontent.com/13363055/58773456-ad23e700-85ef-11e9-8477-62e2d8c6ba55.png)
@tomoya92 一致的，我之前跑别的项目都没出过这个问题。加了参数，跑了一段时间还是停了，报错如图

**Comment by tomoya92** [comment]
@Liuguozhu 这个。。不清楚了，我部署的 demo.yiiu.co 服务好像从来没有主动挂过，除了我更新代码了，会重新发布一下

你要不自己百度一下 😂

**Comment by Liuguozhu** [comment]
@tomoya92 google过了，也是加参数之类的，我再研究下看看
