### ISSUE TITLE
升级springboot版本，将es服务提取出来当插件使用，没有配置es则使用sql like搜索

### ISSUE THREAD

**Issue by YANGJINJUE** [tomoya92/pybbs#92]
![image](https://user-images.githubusercontent.com/32013488/60326868-1c0d1980-99bd-11e9-8987-47099af8b425.png)
这次更新导致这里全部报错，`if (systemConfigService.selectAllConfig().get("search").toString().equals("1"))`

**Comment by tomoya92** [comment]
修复了，那个测试漏掉了，不好意思 https://github.com/tomoya92/pybbs/commit/ba59e3ce8cf26ed18b8ce6cad5b12cbb6156d277
