### ISSUE TITLE
发布话题标签选择在哪里？

### ISSUE THREAD

**Issue by YANGJINJUE** [tomoya92/pybbs#93]
![image](https://user-images.githubusercontent.com/32013488/60378152-d6019580-9a50-11e9-9762-5277191bcb98.png)
发布话题标签选择在哪里？
![image](https://user-images.githubusercontent.com/32013488/60378160-fd586280-9a50-11e9-9685-06a09cbe5f9b.png)
后台自定义标签后，在前端在该标签下发布话题，并没有归类到该标签下？

**Comment by tomoya92** [comment]
嗯，这是个bug，待会我修一下

之前是可以在发帖的时候输入标签的，所以这个功能是好的，用了一段时间之后，发现很多人发帖标签都是乱填的，然后我就把前台发帖的标签给去掉了，这地方就遗漏了一个bug，标签可以在后台编辑帖子时添加上

**Comment by YANGJINJUE** [comment]
好的，标签后台应该加一个添加标签的，前台可以选择哪个标签，也可以申请加入标签，要通过后台审核，可以参考一下。

**Comment by tomoya92** [comment]
标签是根据帖子内容来的，如果在后台加上标签了，前台没有相应的帖子，也不太好，毕竟在前台可以查看网站内都有哪些标签了

审核功能pybbs不会考虑加入，原因有下

1. 没有必要
2. 如果让用户在发帖的时候选择已经存在的标签，如果标签数少还好，多的话，用sql来查就比较慢了，加es这种索引在检索又比较麻烦
3. 当只能让用户自己去选标签的话，那体验就不太好了，万一用户发的帖子没有找到相应的标签，会不爽，还不如不填
4. 当然也可以在让用户选择标签的时候另外加上如果系统没有用户要选的标签，就让用户自己填上，然后再入库，这样就会出现上面我说的现象，标签会非常乱

综上考虑，pybbs不会加你说的审核和在后台添加标签功能，帖子标签只有一个入口，就是在后台编辑帖子的时候加上，这样做用户发帖省心，管理员维护也省心
