### ISSUE TITLE
多线程环境下该变量不能保证原子性?

### ISSUE THREAD

**Issue by YANGJINJUE** [tomoya92/pybbs#95]
![image](https://user-images.githubusercontent.com/32013488/60380695-38bc5680-9a7c-11e9-8686-aae12b47cf4e.png)
在线人数这个并不能保证原子性?建议使用AtomicInteger

**Comment by tomoya92** [comment]
其实这个参数在页面上没有用到，不过已经改成AtomicInteger了，感谢！

**Comment by YANGJINJUE** [comment]
ok.
