### ISSUE TITLE
请问如何配置freemaker可以区分 不同url返回json和html的？

### ISSUE THREAD

**Issue by heqiqi** [tomoya92/pybbs#96]
一直没有看到有类似的配置，只是在HttpUtil.isApiRequest 有一个检测。

**Comment by tomoya92** [comment]
这跟freemarker没有关系，就是那个类做了一个请求头的检测，然后再设置响应类型就可以了

**Comment by heqiqi** [comment]
感谢回复。
我新建了一个controller，继承了BaseApiController，但是最后
` return redirect("/");` 
总是 显示 “redirect:/”,而不是走freemaker的模板，这个是要有配置么？

**Comment by heqiqi** [comment]
感谢，学习了。
