### ISSUE TITLE
IDEA run PybbsApplication的时候，控制台输出报错信息：Access denied for user 'root'@'117.136.122.206' (using password: NO)

### ISSUE THREAD

**Issue by zhongpengqun** [tomoya92/pybbs#98]
IDEA run PybbsApplication的时候，控制台输出报错信息：
2019-10-11 17:25:13 [restartedMain] ERROR c.y.p.c.DataSourceHelper - Access denied for user 'root'@'117.136.122.206' (using password: NO)
2019-10-11 17:25:13 [restartedMain] ERROR c.y.p.c.DataSourceHelper - 创建数据库失败!

但是整个项目都没找到有 117.136.122.206 的字样，数据库怎么会连到这里去呢？

**Comment by tomoya92** [comment]
这是你自己配置的数据库连接吧？

**Comment by tomoya92** [comment]
这错误应该是数据库的用户名或密码不对

**Comment by zhongpengqun** [comment]
代码中数据库ip配置为 139.196.39.xxx(保密)，我发现我手机的ip地址是117.136.122.206， 而我电脑连的是手机的热点。
跑代码的时候，程序没有去连代码中的数据库配置，而是去连手机的IP，很奇怪！

**Comment by zhongpengqun** [comment]
后来我打开电脑的虚拟机，安装了Mysql，代码中数据库ip配置为内网地址 172.20.10.5 ，于是 就好了。

**Comment by tomoya92** [comment]
😄
